### ISSUE TITLE
ServerD.exe Random exiting itself 

### ISSUE THREAD

**Issue by StingMcRay** [Dejauxvue/AnnoCalculatorServer#10]
Dear Devs, 
As mentioned i have experience an odd thing with the ServerD.exe file:
As fare i see, it closing it self on random occasions, however he produce an error msg,
but can not screenshot it, and i do not see an error log (or something) in the directory itself
So, i do not know what it is, and i can not reproduce it, as it happens random many times while i play the game, starting other programs, or even open an second browser....
Sorry i can not give you the error, but i must report this

Kindly regards

*Site note, i have d/l the 4 missing icons and put them into the icons folder, but the above issue was existing before that also already*

**Comment by NiHoel** [comment]
The most likely reason is that Tesseract runs into an unrecoverable error - not even wrapping it into a catch-all helps. Since the last update (due to evaluating the statistics screen) tesseract is called much more frequently, therefore making it more likely to crash.

If you start the program from a terminal window, the output should be kept even if the application crashes.
