### ISSUE TITLE
Resolution 2560x1080

### ISSUE THREAD

**Issue by Pharamond** [Dejauxvue/AnnoCalculatorServer#2]
Hi,
i Try your instruction for this Resolution but it want Work
Pleas have an Eye on this maybe i doing something wrong
I put ALL Files in the image_recon Folder
[image_recon.zip](https://github.com/Dejauxvue/AnnoCalculatorServer/files/3537197/image_recon.zip)

Thx

**Comment by Dejauxvue** [comment]
Hi,

you did everything just fine.
As the server command line says, the detected resolution was 160x28 which is the resolution of the minimized window. So you probably started the server while anno was minimized?
In order to make it work, start anno in full screen windowed mode and start Server.exe afterwards.

I am currently working on this issue and in future release changing resolution should be no problem anymore.

thank you very much for your feedback :)

**Comment by Dejauxvue** [comment]
Should be fixed in release v1.1.3, can you tell me if it works now?

**Comment by Pharamond** [comment]
![Server](https://user-images.githubusercontent.com/54474195/63639059-bae98580-c68f-11e9-99b9-6afe4c181bc9.png)

Not Really, the Srever runs but it schows Can't find Population.
I do as you Say play in Windowed Fullscreen Mode or only in Windowed Mode
Greets
Phara

**Comment by Pharamond** [comment]
Ok find what i did wrong better what i overreading Whoops :)
I have to Hover over the Population then it Works Greatly 
This can now be Closed :)

Many Thx
and by the Way Great Tool and Really Nice Work Thank You
